apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.dockersecret.name}}
  namespace: {{.Release.Namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.dockersecret.dockerConfigJson}}
