apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{include "express-api.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "express-api.labels" . | nindent 4}}
spec:
  podSelector:
    matchLabels: {{- include "express-api.selectorLabels" . | nindent 6}}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{.Values.service.port}}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb
      ports:
        - protocol: TCP
          port: 27017
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{.Values.service.port}}
