apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "express-api.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "express-api.labels" . | nindent 4}}
subjects:
  - kind: ServiceAccount
    name: {{include "express-api.fullname" .}}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{include "express-api.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
