apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "express-api.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "express-api.labels" . | nindent 4}}
rules:
  - apiGroups: ['']
    resources: ['pods', 'configmaps', 'secrets']
    verbs: ['get', 'watch', 'list']
