apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-sonar
spec:
  acme:
    email: {{.Values.certManager.email}}
    server: {{.Values.certManager.server}}
    privateKeySecretRef:
      name: {{.Values.certManager.privateKeySecretRefName}}
    solvers:
      - http01:
          ingress:
            class: nginx
